#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
pipewire &
wireplumber &
pipewire-pulse &
copyq &
picom &
polybar -r mainbar &
polybar -r secondbar &
feh --bg-fill ~/.wallpapers/wallpaper.png &
#crontab ~/.config/bspwm/wallpapercron.cron &
xsetroot -cursor_name left_ptr &
# bspc monitor DisplayPort-0 -d I II III IV V &
# bspc monitor HDMI-A-0 -d VI VII VIII IX X

bspc monitor DisplayPort-0 -d 1 2 3 4 5 &
bspc monitor HDMI-A-0 -d 6 7 8 9 10

xrandr --output DisplayPort-0 --primary --mode 1920x1080 --rotate normal --output HDMI-A-0 --mode 1920x1080 --rotate normal --left-of DisplayPort-0

bspc config border_width 3
bspc config window_gap 5
bspc config top_padding 38

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle false
#bspc config active_border_color \#0CED00
bspc config focused_border_color \#913a1e

bspc config pointer_action1 move
#bspc config pointer_action1 resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a zathura state=tiled
bspc rule -a photoshop state=fullscreen
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
